services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      - DATABASE_URL=postgresql://admin:your_password@db:5432/dua_db
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
