services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_URL=${DB_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
